---
plugin: amazon.aws.aws_ec2

regions:
  - "eu-central-1"

strict: False

keyed_groups:
  - key: tags.Name
  - key: tags.nginx_david_prj_15

filters:
  instance-state-name : running
compose:
  ansible_host: private_ip_address

ansible_ssh_private_key_file: /home/ec2-user/.ssh/id_rsa